//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.EvidenceDocuments = new HashSet<EvidenceDocument>();
            this.Suggestions = new HashSet<Suggestion>();
        }
    
        public int applicationID { get; set; }
        public string applicationDate { get; set; }
        public string reason { get; set; }
        public string requiredAmount { get; set; }
        public Nullable<int> studentId { get; set; }
        public string session { get; set; }
        public string father_status { get; set; }
        public string house { get; set; }
        public string guardian_name { get; set; }
        public string guardian_contact { get; set; }
        public string jobtitle { get; set; }
        public string salary { get; set; }
        [JsonIgnore]
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] 
        public virtual ICollection<EvidenceDocument> EvidenceDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] 
        public virtual ICollection<Suggestion> Suggestions { get; set; }
    }
}
