//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int budgetId { get; set; }
        public Nullable<int> budgetAmount { get; set; }
        public Nullable<int> remainingAmount { get; set; }
        public string budget_session { get; set; }
        public string status { get; set; }
    }
}
