//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Criterion
    {
        public int id { get; set; }
        public string val1 { get; set; }
        public string val2 { get; set; }
        public Nullable<int> policy_id { get; set; }
        public string description { get; set; }
        public Nullable<int> strength { get; set; }
        [JsonIgnore]
        public virtual Policy Policy { get; set; }
    }
}
