//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EvidenceDocument
    {
        public int id { get; set; }
        public Nullable<int> applicationId { get; set; }
        public string image { get; set; }
        public string document_type { get; set; }
        [JsonIgnore]
        public virtual Application Application { get; set; }
    }
}
