//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grader
    {
        public int id { get; set; }
        public Nullable<int> facultyId { get; set; }
        public string session { get; set; }
        public string feedback { get; set; }
        public Nullable<int> studentId { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
    }
}
