//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MeritBase
    {
        public int id { get; set; }
        public Nullable<int> studentId { get; set; }
        public string session { get; set; }
        public Nullable<int> position { get; set; }
        [JsonIgnore]
        public virtual Student Student { get; set; }
    }
}
