//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Applications = new HashSet<Application>();
            this.graders = new HashSet<grader>();
            this.MeritBases = new HashSet<MeritBase>();
        }
    
        public string arid_no { get; set; }
        public string name { get; set; }
        public int semester { get; set; }
        public Nullable<double> cgpa { get; set; }
        public string section { get; set; }
        public string degree { get; set; }
        public string father_name { get; set; }
        public string gender { get; set; }
        public int student_id { get; set; }
        public string profile_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] 
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] 
        public virtual ICollection<grader> graders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore] 
        public virtual ICollection<MeritBase> MeritBases { get; set; }
    }
}
