//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public int id { get; set; }
        public string comment { get; set; }
        public Nullable<int> committeeId { get; set; }
        public int applicationId { get; set; }
        public string status { get; set; }
        public string amount { get; set; }
        [JsonIgnore]
        public virtual Application Application { get; set; }

        [JsonIgnore] 
        public virtual Committee Committee { get; set; }
    }
}
